spring.application.name=Hackathon

server.port=8081

server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true

spring.datasource.url=jdbc:postgresql://localhost:5432/Hackathon
spring.datasource.username=postgres
spring.datasource.password=1506
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
