spring.application.name=Hackathon
<<<<<<< HEAD

server.port=8081

=======
>>>>>>> a3431b788704a4b63007a0fcacf5d2ae859109cd
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true

<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/Hackathon
spring.datasource.username=postgres
spring.datasource.password=1506
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/HackathonDB
spring.datasource.username=postgres
spring.datasource.password=sql
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
>>>>>>> a3431b788704a4b63007a0fcacf5d2ae859109cd
